In [1]:
import pandas as pd
import os

# 폴더 경로 설정
folder_path = './'  # 현재 경로 기준

# 파일 필터링
file_list = [f for f in os.listdir(folder_path) if f.endswith('.csv') and '전기차충전소' in f]

# 데이터프레임 리스트
df_list = []

for file in file_list:
    file_path = os.path.join(folder_path, file)
    try:
        df = pd.read_csv(file_path, encoding='utf-8')  # 기본 utf-8
    except UnicodeDecodeError:
        try:
            df = pd.read_csv(file_path, encoding='utf-8-sig')  # 또는 utf-8-sig
        except UnicodeDecodeError:
            df = pd.read_csv(file_path, encoding='euc-kr')  # 최후의 수단
    df['파일이름'] = file  # 출처 파일 구분용 열 추가
    df_list.append(df)

# 모든 데이터를 하나로 합치기
all_data = pd.concat(df_list, ignore_index=True)

# 미리보기
all_data.head()

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_101908\1829365389.py:21: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='euc-kr')  # 최후의 수단
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_101908\1829365389.py:16: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='utf-8')  # 기본 utf-8

,statNm,statId,chgerId,chgerType,addr,addrDetail,location,lat,lng,useTime,...,kindDetail,parkingFree,note,limitYn,limitDetail,delYn,delDetail,trafficYn,year,파일이름
0,한국광기술원,ME181501,1,6,광주광역시 북구 첨단 벤처로 108번길 9,NaN,NaN,35.231341,126.859822,24시간 이용가능,...,A003,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv
1,롯데마트 수완점,ME181545,1,6,광주광역시 광산구 장신로 98,NaN,NaN,35.190126,126.820343,10:00~23:00,...,E001,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv
2,롯데마트 수완점,ME181545,11,6,광주광역시 광산구 장신로 98,NaN,NaN,35.190126,126.820343,10:00~23:00,...,E001,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv
3,블루핸즈 하남현대자동차서비스,ME183018,1,6,광주광역시 광산구 하남대로 127-10,NaN,NaN,35.181018,126.807449,24시간 이용가능,...,F002,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv
4,기아자동차 진월점,ME183019,1,6,광주광역시 남구 진월동 314-1,NaN,NaN,35.124734,126.897109,24시간 이용가능,...,F002,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv

In [4]:
all_data

,statNm,statId,chgerId,chgerType,addr,addrDetail,location,lat,lng,useTime,...,kindDetail,parkingFree,note,limitYn,limitDetail,delYn,delDetail,trafficYn,year,파일이름
0,한국광기술원,ME181501,1,6,광주광역시 북구 첨단 벤처로 108번길 9,NaN,NaN,35.231341,126.859822,24시간 이용가능,...,A003,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv
1,롯데마트 수완점,ME181545,1,6,광주광역시 광산구 장신로 98,NaN,NaN,35.190126,126.820343,10:00~23:00,...,E001,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv
2,롯데마트 수완점,ME181545,11,6,광주광역시 광산구 장신로 98,NaN,NaN,35.190126,126.820343,10:00~23:00,...,E001,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv
3,블루핸즈 하남현대자동차서비스,ME183018,1,6,광주광역시 광산구 하남대로 127-10,NaN,NaN,35.181018,126.807449,24시간 이용가능,...,F002,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv
4,기아자동차 진월점,ME183019,1,6,광주광역시 남구 진월동 314-1,NaN,NaN,35.124734,126.897109,24시간 이용가능,...,F002,Y,NaN,N,NaN,N,NaN,N,2018,광주시_전기차충전소_전체.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349173,인천교통공사01,ZPZPIT01,2,4,인천광역시 서구 파랑로 105,BRT 통합차고지,차고지 본사 건물 왼쪽 앞,37.300000,126.370000,24시간 이용가능,...,B001,Y,NaN,Y,시설 상황에 따라 이용이 제한될 수 있음,N,NaN,N,2024,인천시_전기차충전소_전체_utf인코딩.csv
349174,인천교통공사01,ZPZPIT01,3,4,인천광역시 서구 파랑로 105,BRT 통합차고지,차고지 본사 건물 왼쪽 앞,37.300000,126.370000,24시간 이용가능,...,B001,Y,NaN,N,시설 상황에 따라 이용이 제한될 수 있음,N,NaN,N,2024,인천시_전기차충전소_전체_utf인코딩.csv
349175,인천교통공사01,ZPZPIT01,4,4,인천광역시 서구 파랑로 105,BRT 통합차고지,차고지 본사 건물 왼쪽 앞,37.300000,126.370000,24시간 이용가능,...,B001,Y,NaN,N,시설 상황에 따라 이용이 제한될 수 있음,N,NaN,N,2024,인천시_전기차충전소_전체_utf인코딩.csv
349176,인천교통공사01,ZPZPIT01,5,4,인천광역시 서구 파랑로 105,BRT 통합차고지,차고지 본사 건물 왼쪽 앞,37.300000,126.370000,24시간 이용가능,...,B001,Y,NaN,N,시설 상황에 따라 이용이 제한될 수 있음,N,NaN,N,2024,인천시_전기차충전소_전체_utf인코딩.csv
349177,인천교통공사01,ZPZPIT01,6,4,인천광역시 서구 파랑로 105,BRT 통합차고지,차고지 본사 건물 왼쪽 앞,37.300000,126.370000,24시간 이용가능,...,B001,Y,NaN,N,시설 상황에 따라 이용이 제한될 수 있음,N,NaN,N,2024,인천시_전기차충전소_전체_utf인코딩.csv

로직 1: 사용자 입력 변수를 기반으로 한 필터링

1차 필터링: 고장나지 않은 충전기만 필터링
- stat 변수에서 2, 3번만 사용 (충전대기, 충전중) (1, 9 통신이상, 상태미확인도 포함해야할까? 개수 확인 필요)
- delYn 변수에서 n인 것들만 사용

### 이 사이에 로직 2에서 구현한 기능 1이 들어가야 함. m km 기반 필터링 ###

2차 필터링: 사용자 입력 변수 기반 필터링
- output: 충전 용량(3, 7, 50, 100, 200)
- chgertype: 충전기 커넥터 유형(01:DC차데모,02: AC완속,03: DC차데모+AC3상,04: DC콤보,05: DC차데모+DC콤보, 06: DC차데모+AC3상+DC콤보, 07: AC3상, 08: DC콤보(완속), 09: NACS, 10: DC콤보+NACS)
- kind: 관련 시설 종류(공공시설, 주차시설 등)
- busid: 충전 사업자(GS 칼텍스, 현대자동차 등)

로직 2: 충전소 스코어링

Note: 경로 좌표들을 받아서 N km 지점마다의 위치 좌표를 구하는 기능은 이후에 구현하고, 지금은 특정 위치 좌표가 주어졌을 때, m km 이내의 충전소 중 top k개를 추려내 반환하는 기능만 구현 예정.
고속도로인지 아닌지 확인할 수 있다고 전달받았는데, 그건 일단 이후에 고도화...
스코어링에 필요한 동적인 상태 변수를 받아와서 업데이트 하는 과정이 필요하지만, 일단은 서버에서 어떻게 돌아갈지 모르기 때문에 업데이트 된 상태라고 가정하고 구현하겠음.

Input: 충전소 추천이 필요한 지점의 위도 및 경도 (a, b)
Output: Input 지점에서 추천하는 충전소 top-k의 dataframe row

구현할 기능 1: input으로부터 m km 이내의 충전소 필터링
구현할 기능 2: 스코어링 식

스코어링에 활용할 변수:
1. 운영시간 ustime: 운영시간에 제한이 없는 충전소에 더 높은 점수 -> input 형식이 다양해서 전처리 필요함, 그리고 의미 있을지 잘 모르겠어서 고민 필요. 도착 예정 시간에 운영중인 충전소를 추천해주는 게 좋을 듯. 
경로 api 팀에 도착 예정 시각도 받아올 수 있는지 문의 -> 가능하면 time in ustime일 때 추천해주면 될 듯
2. 주차 무료 여부 parkingFree: 주차 무료 충전소에 더 높은 점수. 그런데 값이 없는 경우도 많아서...
3. 동적인 충전소 상태 변수: 
    1. 최근 사용 기록이 있는 충전소일수록 잘 작동하고 있다는 증거이므로 해당 충전소를 우선 추천
    2. 현재 시점(혹은 사용자의 예상 도착 시간 기준..?)의 충전소 혼잡 정도(충전중이지 않은 충전기 수/전체 충전기 수)를 계산하여, 충전소 혼잡도가 낮은, 사용이 원활한 충전소를 우선적으로 추천 -> 해야할까?
5. 비용 조건: 충전 요금을 기준으로 저렴한 충전소를 우선적으로 추천
6. 충전기 수: 해당 충전소의 충전기 수가 많은 충전소를 우선적으로 추천
7. 위치 가까운 순으로 높은 점수 부여, 위도 경도 기준으로 haversine library 불러와서 사용